#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/pneumatology/pneumatology-hugo
#+HUGO_SECTION: ./post

#+TITLE: Astral Projection Part 3 - The Images
#+DATE: <2022-05-12>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: astral faith

Moreover, the whole space of the Holy of Holies is fire.

See: [[https://mullikine.github.io/posts/river-of-fire/][Dream: River of Fire - Purification and Transfiguration // Bodacious Blog]]

Now I do not know yet if it is what I have observed.
There is more left to see, I imagine.
The Holy of Holies may be unseen, unless this is a tiny glimpse.

** Summary
Last night I had a very startling lucid dream; almost as vivid in colour and detail as being awake.
Fully conscious but different from previous astral experiences, I wasn't in my own shoes this time.

+ [[https://biblehub.com/bsb/john/14.htm][John 14:1]] :: “Do not let your hearts be troubled. You believe in God; believe in Me as well. In My Father’s house are many rooms. If it were not so, would I have told you that I am going there to prepare a place for you? And if I go and prepare a place for you, I will come back and welcome you into My presence, so that you also may be where I am. You know the way to the place where I am going.” The Way, the Truth, and the Life.

+ [[https://www.biblegateway.com/passage/?version=KJV&search=John+14+-17][John 14:5-23]] :: ... Thomas saith unto him, Lord, we know not whither thou goest; and how can we know the way? 6 Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me. 7 If ye had known me, ye should have known my Father also: and from henceforth ye know him, and have seen him. ... Judas saith unto him, not Iscariot, Lord, how is it that thou wilt manifest thyself unto us, and not unto the world? 23 Jesus answered and said unto him, If a man love me, he will keep my words: and my Father will love him, and we will come unto him, and make our abode with him. ...

+ [[https://biblehub.com/bsb/john/14.htm][John 14:23]] :: 23 Jesus replied, “If anyone loves Me, he will keep My word. My Father will love him, and We will come to him and make Our home with him. 24 Whoever does not love Me does not keep My words. The word that you hear is not My own, but it is from the Father who sent Me. 

+ [[https://www.bibleref.com/1-Corinthians/2/1-Corinthians-chapter-2.html][1 Corinthians 2]] :: My message and my preaching were not with wise and persuasive words, but with a demonstration of the Spirit's power, 5 so that your faith might not rest on human wisdom, but on God's power.

+ [[https://www.biblegateway.com/passage/?search=Colossians+1&version=NKJV][Colossians 1:9-12]] :: 9 For this reason we also, since the day we heard it, do not cease to pray for you, and to ask that you may be filled with the knowledge of His will in all wisdom and spiritual understanding; 10 that you may walk worthy of the Lord, fully pleasing Him, being fruitful in every good work and increasing in the knowledge of God; 11 strengthened with all might, according to His glorious power, for all patience and longsuffering with joy; 12 giving thanks to the Father who has qualified us to be partakers of the inheritance of the saints in the light.

| Incident | Date           | Surroundings       | Identity     | Body              | Other People                       | Incident                                        | Dream type    |
|----------+----------------+--------------------+--------------+-------------------+------------------------------------+-------------------------------------------------+---------------|
|        1 | [[https://mullikine.github.io/posts/astral-projection/][2022-04-02 Sat]] | Blackness          | Myself       | Astral + Physical | Myself                             | Stigmata (Jesus)                                | Astral (self) |
|        2 | [[https://mullikine.github.io/posts/astral-projection-pt-2/][2022-05-03 Tue]] | Blackness          | Myself       | Astral + Physical | Myself and one other (Holy Spirit) | Communion (Holy Spirit)                         | Astral (self) |
|        3 | [[https://mullikine.github.io/posts/astral-projection-pt-3/][2022-05-12 Thu]] | Many public spaces | Holy Spirit? | Astral            | Many people                        | Love (God the Father), or Intimation of the Son | Astral (HS?)  |

---

+ [[https://www.esv.org/John+14/][John 14]] :: 8 Philip said to him, “Lord, show us the Father, and it is enough for us.” 9 Jesus said to him, “Have I been with you so long, and you still do not know me, Philip? Whoever has seen me has seen the Father. How can you say, ‘Show us the Father’? 10 Do you not believe that I am in the Father and the Father is in me? The words that I say to you I do not speak on my own authority, but the Father who dwells in me does his works. 11 Believe me that I am in the Father and the Father is in me, or else wbelieve on account of the works themselves.

See, that the Father's works are seen through Jesus, the Mediator.

---

The third one ever, but different this time in that I was experiencing from another's identity.

I would be lying down in an open public space and as soon as I woke I would immediately, walk up to a person or a group of people,
surging in the Holy Spirit which was dictating all of my thought,
trying to vocalise love and an intense feeling of wanting to rescue people,
people who were just going about their daily lives, but who were receptive, and had faith, welcoming me to come up to them and pray for them.
My own personhood as Shane was not part of my identity and it felt like none of my own self was imparted on this dream.

Two examples, there was a girl with a disfigured face, which I placed my hands on and was healed before my eyes.
There was another of a singer, a young man in a band with anxiety, about to sing on stage, asking for peace. I prayed for this person because this person *should not* feel anxiety - it's evil, and as I walked away I could hear the most beautiful singing. A key part of this one is that I was barely done speaking as they hurried on stage, but the heart had already spoken.

I'd go up to them out of pressing need and heal broken people and pray to God on their behalf, I'd touch them and they would be healed from their affliction, I'd be fighting my body with overwhelming need to pray for them to vocalise what was inside me.

I'd do this continually, waking up to new places and people, and people would say, 'Is this the Holy teacher?' (Giving specific names, the Holy <person's name>).

It was very similar to the 2 astral dreams I have had so far, but
I was in someone else's shoes. It felt like I was living
through someone else' eyes, and part of that imprinted on me because it felt like I experienced it.

** How I was sleeping
I was laying on my back as before with my hands placed one above the other on my chest, like a dove this time. Very comfy.
My blanket wasn't covering my legs, though. When I woke up I could feel what was like a moth fluttering on my left leg.
But I could feel the exact same inner love surging in me while I was awake. That vibrational energy.

** Interpretation
As it has imprinted on me. I've had a glimpse of what it looks like, and I interpret this as instruction and therefore added responsibility.
I wouldn't dismiss the possibility that the dream I had is a vision of my future self. It's possible.
The way is narrow. Do I have to aim for the Holy Spirit to rewrite my spirit entirely?
Possibly. It's possible that I need to *become* love. I would say that there is more work to be done.
It's also open to the possibility that each 'day' in the dream actually happened or will happen.
The only undeniable thing is that it's a glimpse of what it looks like, which is good because it has imprinted on me as some kind of goal.
Like driving a car, we need to see further down the road to drive straight.

+ =Luke 12:42-44= :: The Lord answered, “Who then is the faithful and wise manager, whom the master puts in charge of his servants to give them their food allowance at the proper time? 43 It will be good for that servant whom the master finds doing so when he returns. 44 Truly I tell you, he will put him in charge of all his possessions..."

I imagine this means that we own the treasure, and the treasure is pure spiritual eternal love between the people we interact with.
In this life, we are given instructions. When we actuate in obedience, we are put in charge of it in Heaven.
We are part of it. Jesus teaches us how to do this.

+ =Luke 12:47= :: “And a servant who knows what the master wants, but isn’t prepared and doesn’t carry out those instructions, will be severely punished.

That's huge responsibility!

#+BEGIN_SRC text -n :async :results verbatim code
  (84) Jesus said, "When you see
  your likeness, you are glad. But
  when you see your images which
  came into being before you, and
  which neither die nor are revealed,
  how much you will have to bear!"
#+END_SRC

*** No-one has seen God [directly]
+ [[https://biblehub.com/kjv/john/1.htm][John 1 KJV]] :: 18 No man hath seen God at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him.

+ [[https://books.google.co.nz/books?id=zkFTEAAAQBAJ&pg=PT102&lpg=PT102&dq=is+spirit+imperceptible&source=bl&ots=Yj7IO2lolH&sig=ACfU3U0VgqNowQ1dVx_sZfL1qBoSf2Bfxg&hl=en&sa=X&ved=2ahUKEwi3s6jDprj4AhWeldgFHdY0BZYQ6AF6BAgoEAM#v=onepage&q=is%20spirit%20imperceptible&f=false][Imperceptible Reality: A Longing for Spiritual Vision]] :: The Bible teaches us that no one has seen God; furthermore, God is spirit, and those who worship him must worship in spirit and truth (see John 4:24.), but have you ever wished that you could have a vision or see a hint of God with your eyes? Maybe not get too close, since no one who sees Him could live - but only to be able to observe Him enough to lock the image in your memory banks for future reference, so you'd never doubt again. Then again, if we were granted that experience, I think we'd be petrified.

#+BEGIN_SRC text -n :async :results verbatim code
  intimation
      An indication or hint.
      "the first intimations of trouble"
  
      The action of making something known,
      especially in an indirect way.
      "it took ten years from the intimation of
      a claim to the assessment of damages"
#+END_SRC

I believe the third 'dream' is an intimation of the Father.

** Alternatively, it could be an intimation of the Son
There are hints to this.

- Praying to the Father to =rescue=, for example.

** Bridal chamber
- [[https://blogs.ancientfaith.com/glory2godforallthings/2020/04/13/in-the-maw-of-the-bridal-chamber/][I just read this]]

#+BEGIN_SRC text -n :async :results verbatim code
  The followers of Thomas, like Valentinians,
  should seek the "true wedding" in a spiritual
  bridal chamber.
  
  A similar concept existed in Valentinian
  Gnosticism with the notion of the Bridal
  Chamber, which involved a marriage to one's
  heavenly counterpart. Some mystics take this
  "marriage" as a symbol of the union of the
  human soul with God.
#+END_SRC

Indeed I believe I had this experience.

*** [[http://gnosis.org/naghamm/gop.html][Gospel of Philip]]
I'm not sure about this gospel, but the idea
of 'bridal chamber' seems interesting to me.

Perhaps 'bridal chamber' is that very intimate 'state of mind' of speaking to the Holy Spirit directly as a person.

I do not know. Upon discovering the above link, I truly believe that what I experienced was the =Maw of the Bridal Chamber=.

That is the main thing I want to say.

I do not know about the 'Gospel of Philip' yet. I have not vetted it.

- https://www.angelfire.com/dc/universalism/bridalchamber.html
- https://www.angelfire.com/dc/universalism/theperfectman.html

#+BEGIN_SRC text -n :async :results verbatim code
  A wedding is a re-uniting, or a reconciliation
  into ONE, of the male and the female. The
  bridal chamber is the holy of holies hidden
  behind the veil, in the spirit of the mind,
  where through a vision male and female can
  become One New Perfect Man. Such is the
  imagery of the bridal chamber, Philip, Hebrews
  10:20, Mark 10:8.
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  Such a vision perceived at every level of
  existence renews the mind to a true knowledge,
  transforming us into the image of the One who
  creates the New Perfect Man. In him all things
  are gathered together, and reunited. Such a
  reconciliation of all, illustrated in
  marriage, is the very essence of Paul’s
  Gospel, Colossians 3:10.
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  This is a great mystery hidden with Christ in
  God, Ephesians 5:32.
#+END_SRC

I'll be honest, this is very reminiscent of my experience.

#+BEGIN_SRC text -n :async :results verbatim code
  Truth did not come into the world naked, but
  it came in types and images. The world will
  not receive truth in any other way. There is a
  rebirth and an image of rebirth. It is
  certainly necessary to be born again through
  the image. Which one? Resurrection. The image
  must rise again through the image. The bridal
  chamber and the image must enter through the
  image into the truth: this is the restoration.
  Not only must those who produce the name of
  the Father and the Son and the Holy Spirit, do
  so, but have produced them for you. If one
  does not acquire them, the name ("Christian")
  will also be taken from him. But one receives
  the unction of the [...] of the power of the
  cross. This power the apostles called "the
  right and the left." For this person is no
  longer a Christian but a Christ.
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  A bridal chamber is not for the animals, nor
  is it for the slaves, nor for defiled women;
  but it is for free men and virgins.
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  If anyone becomes a son of the bridal chamber,
  he will receive the light. If anyone does not
  receive it while he is here, he will not be
  able to receive it in the other place. He who
  will receive that light will not be seen, nor
  can he be detained. And none shall be able to
  torment a person like this, even while he
  dwells in the world. And again when he leaves
  the world, he has already received the truth
  in the images. The world has become the Aeon
  (eternal realm), for the Aeon is fullness for
  him. This is the way it is: it is revealed to
  him alone, not hidden in the darkness and the
  night, but hidden in a perfect day and a holy
  light.
#+END_SRC

** Links
+ The Father is love :: https://youtu.be/1QdUhNY6DnY?t=359

** I hope this is me
Only because I believe this has happened to me, not because I want power or responsibility.

I just want to keep faith.

#+BEGIN_SRC text -n :async :results verbatim code
  6 Blessed and holy is the one who shares in
  the first resurrection! Over such the second
  death has no power, but they will be priests
  of God and of Christ, and they will reign with
  him for a thousand years. -Revelation 20:1-6
#+END_SRC