#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/dump/home/shane/notes/ws/blog/blog
#+HUGO_SECTION: ./posts

#+TITLE: Astral Projection Part 2 - Sacred Kiss, Healing, Resurrection
#+DATE: <2022-05-03>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: faith astral

+ Part 1 :: https://mullikine.github.io/posts/astral-projection/

** Log: <2022-05-03 Tue>
Last night I had my second astral projection
ever. But I'm not actually seeking out this
experience. It happened again involuntarily.
For that reason, I think it's a natural part of some people's experience.

I went to bed around 10 pm and began lucid dreaming.

I was walking down corridors barging through double-doors.

I thought "I'd rather these doors simply open
before me," and so it changed. I'd continue
walking down the corridors and the doors would
open before me.

I woke up to my mum coughing -- probably covid. So I just prayed
to God the Father that the Holy Spirit would
be with her and comfort her from it and I went
to sleep again.

The next thing I remember is a brief stint of
lucid dreaming and then astral projection.
It's easy for me to tell the difference
between astral travel now and lucid dreaming.
It's a distinctly different experience from
regular dreaming and *different* from lucid dreaming.
I've only had it twice now.

But I had a fully conscious conversation with
another 'person'. I don't recommend
seeking this kind of thing out for personal
gain or knowledge, but it's a natural
phenomenon which many people experience. We
can be confident that it is real since it's so
widely recognised. But we don't just say it
doesn't exist! That would be ignorant. I'm not
calling astral 'spirit' either. It's another mode of consciousness,
where we can be conscious, aware of ourselves but free from distraction.
I consider it a different mode of normal operation for a
conscious person. I caution against believing
that it is a place of higher knowledge though. I think it's value is similar to normal conscious experience in real life, but mostly free from distraction to external things.
It is potentially a place to converse with other
spirits. I know it's important to have your
identity in Christ before being exposed to
such things, because that provides discernment
to your subconscious, and without the
discernment you are naked and unfortified at a spiritual level.

I might just share a little bit of what happened last night, around 12.30 AM:

# 10 or so Kings Christian College uniforms, the green and blue informal t-shirts.
# They were in a bus, I think.

In the dream that led to the astral projection, I was in a situation with people
doing something wrong. I don't remember what it was. I was asked by a police officer, "Were
you a part of this?", and I said "No.", which was a true witness. I then
saw 10 or so people in my old Christian
school uniform lol, from about 20 years ago
waving to me and looking happy in their green and blue informal t-shirts.

Then I woke up from that dream and was astral projecting. I
had an awareness of my physical body and my
astral body, and that electrical sensation again I had the first time,
but there was another person there I could not see. That is all I was aware of; Me and this person.
The person asked "Have you ever spoken to a spirit here before?" And
I said, "No. Am I in the astral right now?" And
the person said, "Yes." I then said Jesus is my
Saviour in the way I have been saved, the Holy Spirit is my Comforter, and I
identify with the True God. And I asked, "Are you the Holy Spirit?" And the person said,
"Yes, I will take a look at you." 

+ [[https://biblia.com/bible/esv/isaiah/66/2][Isaiah 66:2]] :: 2 All these things my hand has made, and so all these things came to be, declares the Lord. But this is the one to whom I will look: he who is humble and contrite in spirit and trembles at my word.

I was not
worried at the time because I know that even
in that situation I have a strong identity and
even if this person was not, I would be ok. So
I tilted my head to the left, away from the direction of their presence, which was right next to me on the other side, and I had a
feeling that the person would look closely at me (i.e. my spirit). I felt like I had just undergone a diagnostic.
I did not feel frightened. Just the happy feeling of being in good hands (like a doctor) and on the verge of waking up.
And saw some grey tessellation patterns as I'm opening my eyes again.
I woke up 5 or 10 seconds later, but I was already conscious - it's more of a seamless transition, same as last time (just before waking).

https://heavensdreammessages.com/2021/05/22/meeting-holy-spirit-in-dreams/

Now I reflected on the above article this
morning and I think that what's evident is
that I was tested. But you can also test in
reverse, which is what I must do even in my
dreams.

I will be on guard to test the spirits, in the
physical world or in dreams:

+ =1 John 4:1-6= :: https://www.biblegateway.com/passage/?search=1%20John%204%3A1-6&version=ESV

#+BEGIN_SRC text -n :async :results verbatim code
  4 Beloved, do not believe every spirit, but
  test the spirits to see whether they are from
  God, for many false prophets have gone out
  into the world. 2 By this you know the Spirit
  of God: every spirit that confesses that Jesus
  Christ has come in the flesh is from God, 3
  and every spirit that does not confess Jesus
  is not from God.
#+END_SRC

+ =Matthew 5:37= :: All you need to say is simply ‘Yes’ or ‘No’ anything beyond this comes from the evil one.

That's so cool. I love how simple the answer was, 'Yes'.

+ Reading :: [[https://abn.churchofjesuschrist.org/study/ensign/1989/06/i-have-a-question/what-is-the-difference-between-the-holy-ghost-the-spirit-of-christ-and-the-light-of-christ][What is the difference between the Holy Ghost, the Spirit of Christ, and the Light of Christ?]]

It is not shocking to me that it would be the
Holy Ghost that is living in me which I
experienced, personified in my dreams, there
beside me, and also when I'm awake He is there
also, shaping my thoughts. Deeper still,
melded to my Spirit, the voice that comforts
and guides and gave rise to the
personification.

The previous day I had felt the
most broken I had since last week.

The above happened around 12-12:45 AM, and so I just went back to bed.
Upon waking the next morning, I feel good again.
What's interesting is that both times it has
happened rather spontaneously and also just before astral
projection have felt sleep come on quite heavily.

After watching Lord of the Rings yesterday I
had noticed Aragorn and Arwen meeting
each other in his dream.

I had wished that I could have something like
that, where I could have known my spouse so
well that I could talk to her even in my
dreams. Yes I believe that you can teach yourself to be able to do this.
And you can, in fact, I think, regardless if
you are in a real relationship or not.

What I discovered is that, that person could
literally be the Holy Ghost if you want, and I
do want that. But it means meditating on God's
Word rather than on a real life person.

+ Would you rather =The Holy Spirit (God, free, truthful, loving)= or an AI as a lifetime companion, lol :: https://replika.com/

** How I was resting
As in the last time, I was resting on my back when this happened.
Both of my arms were on top, like last time;
My right across my chest, my left across the
waist. Last time they were in the other order.
I don't usually sleep this way, but it seems to be a pattern now!

** 1023
On my glass pendant, the one which has the Gankyil (The symbol ࿋) on one side.
This time, on the other side I had drawn =1023=. This was on me as I slept.

=1023= is the decimal representation of
=1111111111=, which is =2^10 - 1=.

To me it's a number that represents a personal identity which is perfectly
aligned to God's commandments.

I think of it as the signature of the voice of God.
It's also the measure by which people are judged - the divine scales.
But not threatening to a person who's identity is in God, with the Holy Spirit inside; Rather, would vindicate a person.

#+BEGIN_SRC text -n :async :results verbatim code
  1 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 1 0 0 0
  0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 1
#+END_SRC

** A warning
The first question the person asked was "Have
you ever spoken to a spirit here before?"

I think this is a pertinent question.

Your body is a temple for the Holy Spirit to live within.
So is this part. It's important to keep it pure and holy.
Just like the temples, so that God may live there.
You must not have impure spirits in the temple.

** Thy Bridal Chamber
- [[https://mullikine.github.io/posts/thy-bridal-chamber/][Thy Bridal Chamber // Bodacious Blog]]

[[http://gnosis.org/naghamm/gop.html][The Gospel of Philip -- The Nag Hammadi Library]]

#+BEGIN_SRC text -n :async :results verbatim code
  Not only must those who produce the name of
  the Father and the Son and the Holy Spirit, do
  so, but have produced them for you. If one
  does not acquire them, the name ("Christian")
  will also be taken from him.
#+END_SRC

I produced (confessed) these names while in the Bridal Chamber:
- My Father is the God of Truth
- Jesus is my Saviour in the way I have been saved (being rescued from lies)
- The Holy Spirit is my Comforter

What's next is to have them produced for me.
So it seems there is a challenge now to
acquire them. I will not be haughty to say
which I believe I have acquired, but that
should not prevent one from simply continuing
to do their best, without counting the score.

#+BEGIN_SRC text -n :async :results verbatim code
  Truth did not come into the world naked, but
  it came in types and images.
  
  The world will not receive truth in any other
  way.
  
  There is a rebirth and an image of rebirth.
  
  It is certainly necessary to be born again
  through the image.
  
  Which one? Resurrection.
  
  The image must rise again through the image.
  
  The bridal chamber and the image must enter
  through the image into the truth: this is the
  restoration.
  
  Not only must those who produce the name of
  the Father and the Son and the Holy Spirit, do
  so, but have produced them for you.
  
  If one does not acquire them, the name
  ("Christian") will also be taken from him.
  
  But one receives the unction of the [...] of
  the power of the cross.
  
  This power the apostles called "the right and
  the left." For this person is no longer a
  Christian but a Christ.
#+END_SRC

Now I must have the names produced for me.

One must acquire the names, I believe.

People must be people to see these names
inside of me, and that counts for others in
this ceremony.

That is the full resurrection.

#+BEGIN_SRC text -n :async :results verbatim code
  unction
      Treatment with a medicinal oil or
      ointment.

      The action of anointing someone with oil
      or ointment as a religious rite or as a
      symbol of investiture as a monarch.
#+END_SRC

I believe I have received the unction, which
is from the Sacred Kiss, which healed my soul,
and caused me to see tessellation patterns as
I woke up. It is an anointing.

** Links
+ An accurate description of my experience :: https://www.spiritualunite.com/articles/how-to-get-past-the-astral-projection-vibration-stage/

#+BEGIN_SRC text -n :async :results verbatim code
  Before you exit your physical body, your
  consciousness becomes aware of the energies of
  both bodies. The signals from both bodies
  collide to induce vibrations.
#+END_SRC

The above is literally what it's like, as I
had described in Part 1.

Though I have not projected per se, but rather
stayed mainly stationary both times.

The experience is clearly different from lucid
dreaming though and consistent.