#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/dump/home/shane/notes/ws/blog/blog
#+HUGO_SECTION: ./posts

#+TITLE: Jesus is the risen Christ, the Lamb of God, who died to take away the sins of the world
#+DATE: <2022-07-02>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: faith

** Public declaration
I publicly declare to all that Jesus is the risen Christ
who died for my sin. He is the Lamb of God who
was slain to take away the sin of the world.

** My testimony is True
- Jesus is at the cornerstone
- Jesus' gospel is the cornerstone of my own

*** Jesus' gospel is the cornerstone of the gospels of the apostles
It's important to mention here at the top, the
Gospel of Jesus Christ.

I want to start with this so you can understand the Tapestry of Truth with respect to it as the authoritative message.

+ =John 3:17= :: For God did not send His Son into the world to condemn the world, but to save the world through Him.

#+BEGIN_SRC text -n :async :results verbatim code
  The word gospel means “good news,” so the
  gospel of Christ is the good news of His
  coming to provide forgiveness of sins for all
  who will believe (Colossians 1:14; Romans
  10:9).
  
  Since the first man’s sin, mankind has been
  under the condemnation of God (Romans 5:12).
  
  Because everyone breaks God’s perfect law by
  committing sin, everyone is guilty (Romans
  3:23).
  
  The punishment for the crime of sin is
  physical death (Romans 6:23) and then an
  eternity spent in a place of punishment
  (Revelation 20:15; Matthew 25:46).
  
  This eternal separation from God is also
  called the “second death” (Revelation
  20:14–15).
  
  The bad news that all are guilty of sin and
  condemned by God is countered by the gospel,
  the good news of Jesus Christ.
  
  God, because of His love for the world, has
  made a way for man to be forgiven of their
  sins (John 3:16).
  
  He sent His Son, Jesus Christ, to take the
  sins of mankind on Himself through death on a
  cross (1 Peter 2:24).
  
  In placing our sin on Christ, God ensured that
  all who will believe in the name of Jesus will
  be forgiven (Acts 10:43).
  
  Jesus’ resurrection guarantees the
  justification of all who believe (Romans
  4:25).
#+END_SRC

I want to describe the Good News as best as I can, but
in a way that is a little bit different to what you'd normally read.

+ [[https://biblehub.com/john/3-8.htm][John 3:8]] :: The wind blows wherever it wants. Just as you can hear the wind but can’t tell where it comes from or where it is going, so you can’t explain how people are born of the Spirit.”

I believe it's all about becoming a truthful person.

If you love truth (not falsehood), then you already have the ears, so let him hear who can hear!

- https://biblehub.com/john/12-47.htm
- https://www.gotquestions.org/gospel-of-Jesus-Christ.html

The following is my understanding of the
gospel of Jesus but wrapped up in philosophy and math.

+ [[https://www.biblegateway.com/passage/?search=Colossians+2&version=KJV][Colossians 2]] :: 8 See to it that no one takes you captive through hollow and deceptive philosophy, which depends on human tradition and the elemental spiritual forces of this world rather than on Christ.

*** Spiritual circumcision
Spiritually, this is a bit like removing the
spiritual corruption/gangrene so your spirit
can be knitted with the body of Christ.

Souls may be knit together through love.

+ [[https://www.biblegateway.com/passage/?search=1%20Samuel%2018&version=ESV][1 Samuel 18:1]] :: 18 As soon as he had finished speaking to Saul, the soul of Jonathan was knit to the soul of David, and Jonathan loved him as his own soul. 

+ [[http://www.earlychristianwritings.com/thomas/gospelthomas25.html][Thomas 25]] :: (25) Jesus said: Love your brother as your soul; watch over him like the apple of your eye.

Christian brothers and sisters have their souls knitted together.

+ [[https://www.biblegateway.com/passage/?search=Colossians+2&version=KJV][Colossians 2:2, KJV]] :: That their hearts might be comforted, being knit together in love, and unto all riches of the full assurance of understanding, to the acknowledgement of the mystery of God, and of the Father, and of Christ;

But before your soul can be knitted with Jesus' soul, you must prepare your heart and spiritual identity.

This is a 2-stage process:
- Baptism of water
- Baptism of spirit

*** Baptism of water
- https://www.christianity.com/wiki/christian-life/what-does-living-water-mean-in-the-bible.html

#+BEGIN_SRC text -n :async :results verbatim code
  John proclaims baptism of repentance for the
  forgiveness of sin, and says another will come
  after him who will not baptize with water, but
  with the Holy Spirit.
#+END_SRC

You can use the 10 commandments to clean your spirit - they're the =actions= of the heart.
For example, =mixing= is an action when cooking.

If you do the actions with the heart you will
clean your heart. And you'll be able to notice
God; Having swept your house, you become
eligible to have the guest live inside (The Holy Spirit).

The 10 commandments point to an impossible standard
which people need a sacrifice for to be forgiven of transgressions, since we are not perfect, until we are perfected with Jesus' spirit knit with our own.

+ =Baptism of repentance= :: Frustratingly, the way the gospel (good news) is presented in the modern-day is usually
    in such a way that it first condemns to make you *feel* guilty about things which you innocently do, and feels arbitrary,
    then to say you can be forgiven and be guilt-free if you only believe in Jesus for forgiveness.
    
This simulation of guilt and then forgiveness
is a bit like a 'baptism' (submersion and
emersion), but I would say this not a complete way to baptise.

The Jews who John the baptist preached to would've already been aware of the 10 commandments, and that is the difference - this part cannot be skipped.

Repentance is obedient following of commandments.
Baptism of water is a declaration that a person will repent.
When a person repents, they learn of God's character and what it's like to be Jesus when they are persecuted.

This puts the person into a primed position to be baptised by the Holy Spirit.

+ =Thomas Saying 69= :: (69) Jesus said, "Blessed are they who have been persecuted within themselves. It is they
  who have truly come to know the father. Blessed are the hungry, for the belly of him who
  desires will be filled." 

In my theory, rather than merely telling someone they are guilty, they must first learn to walk in the commandments to *learn who God is* from *experience*.
A person must learn who God the Father is and who the Son is, by way of emulation of their character, through their words and commands.
This makes the understanding *deeply rooted*, not merely of understanding of unattainable spiritual perfection, but to understand at which point of being persecuted what it's like to be Jesus.

+ =1 John 2:3-6= :: Now by this we know that we know Him, if we keep His commandments. He who says, "I know Him," and does not keep His commandments, is a liar, and the truth is not in him. But whoever keeps His word, truly the love of God is perfected in him. By this we know that we are in Him. He who says he abides in Him ought himself also to walk just as He walked.

The experience is different for different people; This is like submersion and re-emersion in that it's a rite of passage.

I don't think a water baptism is strictly necessary
but I'm *convinced* that the actions of the heart are, which the ceremony is supposed to set into motion.
The knowledge of God's character is important to understand before an encounter with Jesus.
The mere idea of God's character of but the personal experience of it in relation to you.

John the baptist came to prepare the way for the Lord Jesus.

=Mark 1:1-9=

#+BEGIN_SRC text -n :async :results verbatim code
  “I will send my messenger ahead of you,
      who will prepare your way”[c]—
  “a voice of one calling in the wilderness,
  ‘Prepare the way for the Lord,
      make straight paths for him.’”
#+END_SRC

In summary, the rite of passage which water baptism represents is needed in order to be born again of spirit, I think.

It's a two-stage process.
The end result is being born of God (the Christian God).

# ** Theurgy
# *** Prayer
# #+BEGIN_SRC text -n :async :results verbatim code
#   ¶: Offer Not an Earthly Prayer or Sacrifice
#   Jesus said, "First must the one who prayeth, who offereth his prayer,
#   well consider his gift to see whether there be any spot found in it; and
#   then shall he offer it, that his offering remain not upon the earth."
  
#   [Aphrahat]
# #+END_SRC

# When speaking to God the Father, ensure that the words spoken are without
# earthly blemish, and that the prayer is true in all the heart.

# *** Faith commands
# #+BEGIN_SRC text -n :async :results verbatim code
#   Jesus said, "If two shall come together as one, and they say unto the
#   mountain, 'Pick thyself up and cast thyself into the sea,' it shall be
#   done."

#   [Didascalia 3:7:2]
# #+END_SRC

# You need complete integrity of heart and action.
# Spirit and soul must be working in consonance; None of dissonance, fear, doublethink nor doubt. In integrity all the way to spirit.
# This means without any doubt.

# Let's continue...

*** My gospel is based on Jesus' gospel
- [[https://mullikine.github.io/posts/the-tapestry-of-truth/][The Tapestry of Truth // Bodacious Blog]]

I do not lie.