#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/pneumatology/pneumatology-hugo
#+HUGO_SECTION: ./post

#+TITLE: The Reclamation of Earth
#+DATE: <2022-07-06>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: faith

** Today
Today I woke up and had a vision of my angel trumpet.
It started like this:
- First there was a flash of white light
- A second later there was another flash, but this time of my trumpet

The trumpet does not belong to me, but belongs to the holy angel which I am united with through the Bridal Chamber - that may be Jesus Himself, but I do not know - all I know is the Holy Spirit is inside me.
I'm united with an =angel of the Saviour=. Now the term =angel of God= has sometimes been used.
Simply, I'm soul-bonded with God. I do not know the precise details.

The electrician was coming over today and needed to do some work in my room.
My floor was absolutely covered with rubbish, my clothes etc. just like in the
Gospel of Thomas; Literally, a person has to care so little for material things in order to become like this; But instead, in true procrastination clean up the temple before the electrician comes; Cleaning up for the electrician to fix the lights of this house is homologous to repairing the lights of the soul.

I knew the trumpet vision was angel radio again asking me to do a couple of things.
Firstly, I must rest my angel trumpet (metaphorically) and tend to my room, to prepare for the electrician to come.
Secondly, I must take my trumpet with me.

- [[https://mullikine.github.io/posts/dream-a-thief-and-liar-trying-to-escape/][Dream: A Thief and Liar and bad Caretaker trying to Escape. You've got to know Jesus // Bodacious Blog]]

Multiple symbology here:

Firstly Jesus comes like a Thief in the night.
This is a theme. I believe it is extremely soon now.

Jesus is the Son of God, the Lamb of God, the sacrifice that God made, not just for me but for everyone.
Jesus is my Saviour in the way I have been saved, which was through Him, and God drew me to Him.
I =worked out= my salvation from active seeking. Jesus is the Way, but you must seek from the heart.
My salvation came through challenging lies in myself, and overcoming by listening to what is True; To knowing what Love is.

+ [[https://biblehub.com/philippians/2-12.htm][Philippians 2:12]] :: Therefore, my dear friends, as you have always obeyed—not only in my presence, but now much more in my absence—continue to work out your salvation with fear and trembling,

It is a gift.

Like Peter, I had a dream of being freed by an Angel, and the prison was Lies and Sin.

- [[https://mullikine.github.io/posts/astral-projection-pt-2/][Astral Projection Part 2 - Sacred Kiss, Healing, Resurrection // Bodacious Blog]]

A person can spiritually die in this life, meet Jesus in the bridal chamber and be resurrected early. I'm sure this is the truth; It's what happened to me.
Then they will never taste [the second death] (Hell), as the Gospel of Thomas says.

If a person dies in this life without becoming truth through being saved by Jesus then they sit on their truth in Sheol (the place of the dead).
I've astrally projected to Sheol [[https://mullikine.github.io/posts/astral-projection/][when I met Jesus]], I believe.

When the final judgement arrives the truth which those people sat on is evaluated at judgement.

God is reclaiming the Earth in stages, and [[https://mullikine.github.io/posts/apology/][truth is sometimes reclaimed]] incrementally to gain an edge over the enemy.

In my dream there were two road cones blocking a path.
They were also two short stone pillars (altars).

After cleaning my room today I took the angel trumpet with me and walked down the path from my house. Two road cones were at the top of the staircase. One of the cones had 'Isaac' written on it.

I remembered Abraham and Isaac. Thus I decided that I will wait there for God.

So I began listening to the Gospel of Thomas and stayed approximately 1 hour. At this time two Christians I had never seen before came up to me and asked me if I was Shane.

# I then shared my knowledge with them. Firstly, I believe I have soul bonded with God and hold an angel trumpet.

I returned home my whole room including the hidden places had been uncovered.
So too I believe that that which is hidden deep in my spirit will eventually become manifest.
But having died with Jesus and with a resurrected spirit at my most truthful point and in the astral realm and specifically [in this place] the bridal chamber, I was also simultaneously repentant and reliant on Jesus.
I will not go back there if I hold out to the end. I am a living spirit now!

+ [[http://www.earlychristianwritings.com/thomas/gospelthomas5.html][Thomas 5]] :: (5) Jesus said, "Recognize what Is before your face, and that which is hidden from you will be revealed. For there is nothing hidden that will not become revealed."

+ [[http://www.earlychristianwritings.com/thomas/gospelthomas6.html][Thomas 6]] :: Jesus said, "Do not tell lies, and do not do what you hate, for all things are revealed before heaven. For there is nothing hidden which will not become manifest, and nothing covered will remain without being uncovered."

This is similar to preparing the temple of a person's heart, because the master of the house will come at me of the Kingdom of Darkness, because I want to steal his possessions (human lives) back for Jesus.

*** The disciples of Jesus are like children
When the owners of the field come, they will say: Leave us our field.
The disciples of Jesus pass through this moment.
We strip naked. The hidden things become revealed, and we pass through without shame.

We bind that which is our Truth in Heaven.
Like my red thread/ribbon of fate, I believe.
The treasure we have collected by acts of charity are sown and reaped on the other side.

[[http://www.earlychristianwritings.com/thomas/gospelthomas21.html][Thomas 21]]
- [[https://mullikine.github.io/posts/gospel-of-thomas/][An exergesis of the 'Gospel of Thomas' // Bodacious Blog]]

#+BEGIN_SRC text -n :async :results verbatim code
  (21) Mariham said to Jesus: Whom are your
  disciples like? He said: They are like little
  children who have settled in a field which
  does not belong to them.
  
  When the owners of the field come, they will
  say: Leave us our field.
  
  They are naked before them, in order to leave
  it to them and give them (back) their field.
  
  Therefore I say: If the master of the house
  knows that the thief is coming, he will keep
  watch before he comes, and will not let him
  dig through into his house of his kingdom to
  carry off his things.
  
  You, then, be watchful over against the world;
  gird your loins with great strength, that the
  robbers may find no way to come at you.
  
  For the advantage for which you look, they
  will find.
  
  May there be among you a man of understanding!
  When the fruit ripened, he came quickly, his
  sickle in hand, and reaped it.
  
  He who has ears to hear, let him hear.
#+END_SRC

The master of the house of this world is Satan.

+ [[https://www.biblegateway.com/passage/?search=Revelation%2016%3A15%2CMatthew%2024%3A43%2C1%20Thessalonians%205%3A2%2C1%20Thessalonians%205%3A4%2C2%20Peter%203%3A10&version=ESV][Revelation 16:15]] :: 15 “Behold, I am coming like a thief! Blessed is the one who stays awake, keeping his garments on, that he may not go about naked and be seen exposed!”

The garments are the garments of salvation.

+ [[https://dailyverses.net/isaiah/61/10][Isaiah 61:10]] :: I delight greatly in the Lord; my soul rejoices in my God. For he has clothed me with garments of salvation and arrayed me in a robe of his righteousness, as a bridegroom adorns his head like a priest, and as a bride adorns herself with her jewels.

We are righteous through Jesus' blood for the forgiveness of our sins, which we ask to be covered with.
I may have drunk a lot of sacramental wine by the way.

+ [[https://biblia.com/bible/esv/revelation/3/5][Revelation 3:5]] :: The one who is victorious will, like them, be dressed in white. I will never blot out the name of that person from the book of life, but will acknowledge that name before my Father and his angels.

Jesus is coming like a thief.

** My realisation - I am already resurrected
This means I am one of the Elect.
I have died spiritually, through sin, but I've been resurrected through Jesus, after praying to him in my place of death.

This was predestined to take place.

- [[https://mullikine.github.io/posts/thy-bridal-chamber/][Thy Bridal Chamber // Bodacious Blog]]

I have already been resurrected, through Jesus.
I will not see the place of the dead again, nor experience Hell.
I must remain True to Jesus.
I must stay True, humble and live a life following Jesus' (God's) voice

** God collects treasure - He sifts the Heaven and the Earth
- https://www.acton.org/pub/commentary/2019/03/06/gods-reclamation-project
- https://www.theologyofwork.org/new-testament/hebrews/shaking-things-up-hebrews-1218-29

** Relighting the world
My parents started the chimney fire.
I now sit here trying to relight the world.
I will describe as best as I can the process for others to follow.

*** [[http://www.earlychristianwritings.com/thomas/gospelthomas10.html][Thomas 10]]
Eventually the world will burn in the Truth.

#+BEGIN_SRC text -n :async :results verbatim code
  (10) Jesus said, "I have cast fire
  upon the world, and see, I am
  watching it until it blazes."
#+END_SRC