#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/pneumatology/pneumatology-hugo
#+HUGO_SECTION: ./post

#+TITLE: The Sword of the Spirit - A pricked heart
#+DATE: <2022-07-04>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: faith pneumatology

** Summary
I really need to mention the Sword of the Spirit.

I have experienced the =pricked heart= many
times, and currently right now, and so I need
to write about it.

#+BEGIN_SRC text -n :async :results verbatim code
  Many a minister, some saints, have claimed to
  be speaking God’s message and are not really
  uttering His message. Inside them are
  ‘prickings’ and though they often ignore them,
  they are truly wounded, for the ‘idle words’
  that they spoke are bringing an ‘accounting’,
  God is pricking their hearts.
#+END_SRC

I'm convicted that I sometimes speak without
conviction of the Holy Spirit; Please just
follow the Holy Spirit's voice for yourself -
it's the most important thing to develop that
relationship.

** I am not perfect, and I am still learning!
I'm new to all of this!

I say this because as I write and learn I
discover new things, remove old beliefs, but I
am building my mind maps and belief system
dynamically (as I go along), for proof.

- [[https://www.armyofprophets.com/post/693-what-is-that-sudden-pain-in-your-heart-8486979][693. WHAT IS THAT SUDDEN PAIN IN YOUR HEART? - GOD's  ARMY,  CONTENDING for the FAITH]]

It feels like a little needle 'pricking the heart'.
Literally.

When Peter stood and preached on the day of Pentecost, it says the hearers were ‘pricked in their heart’:

+ Acts 2:37 (KJV) :: Now when they heard this, they were pricked in their heart, and said unto Peter and to the rest of the apostles, Men and brethren, what shall we do?