#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/pneumatology/pneumatology-hugo
#+HUGO_SECTION: ./post

#+TITLE: Thy Bridal Chamber
#+DATE: <2022-06-29>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: faith christianity gnostic

These were spontaneous and God-given experiences over Easter 2022.

According to the [[https://mullikine.github.io/posts/gospel-of-philip/][Gospel of Philip]], the sacrament of the Bridal Chamber is not *necessary* for redemption!

#+BEGIN_SRC text -n :async :results verbatim code
  "Baptism is 'the holy' shrine.
  Redemption is 'holy of the holy'.
  'The holy of the holies' is the bridal chamber".
#+END_SRC

Also, it's definitely possible to go sin after
the bridal chamber - but we don't make a practice of it.

Sin is not the desirable thing to do - it's far more satisfying to remain faithful!
But it's still challenging sometimes because the world is unjust.

#+BEGIN_SRC text -n :async :results verbatim code
  redemption
      The action of saving or being saved from
      sin, error, or evil.
      "God's plans for the redemption of his
      world"
#+END_SRC

---

+ [[https://www.biblegateway.com/passage/?search=2%20Corinthians%2011&version=NIV][2 Corinthians 11]] :: I promised you to one husband, to Christ, so that I might present you as a pure virgin to him.

--

- [[https://mullikine.github.io/posts/astral-projection/][Astral Projection Part 1 - Death with Jesus // Bodacious Blog]]
- [[https://mullikine.github.io/posts/astral-projection-pt-2/][Astral Projection Part 2 - Sacred Kiss, Healing, Resurrection // Bodacious Blog]]
- [[https://mullikine.github.io/posts/astral-projection-pt-3/][Astral Projection Part 3 - The Images // Bodacious Blog]]

---

The spiritual marriage of man to Christ
represents our union with God by
Grace, the death of the old man, and the
restoration of the Divine Image.

This lofty and unfathomable mystery moves
wholly away from any of the literal (and thus
dangerous) marital images that abound in
Western Christianity.

---

+ [[https://mullikine.github.io/posts/gospel-of-philip/][Gospel of Philip]] :: He said on that day in the thanksgiving, "You who have joined the [[https://mullikine.github.io/posts/astral-projection/][perfect light]] with the [[https://mullikine.github.io/posts/astral-projection-pt-2/][Holy Spirit]], unite the angels with us also, as [[https://mullikine.github.io/posts/astral-projection-pt-3/][being the images]]." Do not despise the lamb, for without it, it is not possible to see the king.

The images could also mean the [[https://mullikine.github.io/posts/dream-discernment-of-judgement/][image of the androgyne]].
It can also mean the [[https://mullikine.github.io/posts/gospel-of-thomas/][image of Christ]].

** [[https://www.bible.com/bible/compare/HEB.10.19-25][Hebrews 10:19-25]]

Be sincere, meek, loving and facetious, but
above all things =True=. In everything be
=True= - just be like Jesus and you will be
ready. God will allow you to enter the Bridal
Chamber. Seek Jesus like Children, and
boldness will come from sincerity.

#+BEGIN_SRC text -n :async :results verbatim code
  19 Therefore, brethren, having boldness 6 to
  enter the Holiest by the blood of Jesus, 20
  by a new and oliving way which He consecrated
  for us, through the veil, that is, His flesh,
  21 and having a High Priest over the house of
  God, 22 let us pdraw near with a true heart
  qin full assurance of faith, having our hearts
  sprinkled from an evil conscience and our
  bodies washed with pure water. 23 Let us hold
  fast the confession of our hope without
  wavering, for He who promised is faithful. 24
  And let us consider one another in order to
  stir up love and good works, 25 not forsaking
  the assembling of ourselves together, as is
  the manner of some, but exhorting one another,
  and tso much the more as you see uthe Day
  approaching.
#+END_SRC



#+BEGIN_SRC text -n :async :results verbatim code
    The males are they which unite with the souls
    which inhabit a female form, but the females
    are they which are mingled with those in a
    male form, though one who was disobedient.

    And none shall be able to escape them, since
    they detain him if he does not receive a male
    power or a female power, the bridegroom and
    the bride.

    One receives them from the mirrored bridal
    chamber.
#+END_SRC

** Vesture of my soul
#+BEGIN_SRC text -n :async :results verbatim code
  Thy bridal chamber I see adorned, O my Savior,
  and I have no wedding garment that I may enter.
  O Giver of Light, enlighten the vesture of my soul, and save me.
#+END_SRC

** [[http://gnosis.org/naghamm/gop.html][Gospel of Philip]]

+ [[http://gnosis.org/naghamm/gop.html][Gospel of Philip]] :: A bridal chamber is not for the animals, nor is it for the slaves, nor for defiled women; but it is for free men and virgins.

---

- [[http://gnosis.org/naghamm/gop.html][The Gospel of Philip -- The Nag Hammadi Library]]

The homology of the physical temple to the
temple of your heart.

#+BEGIN_SRC text -n :async :results verbatim code
  There were three buildings specifically for
  sacrifice in Jerusalem.

  The one facing the west was called "The Holy".

  Another, facing south, was called "The Holy of
  the Holy".

  The third, facing east, was called "The Holy
  of the Holies", the place where only the high
  priest enters.

  Baptism is "the Holy" building.

  Redemption is the "Holy of the Holy".

  "The Holy of the Holies" is the bridal
  chamber.
#+END_SRC

See: [[https://mullikine.github.io/posts/the-five-sacraments/][The Five Sacraments // Bodacious Blog]]

#+BEGIN_SRC text -n :async :results verbatim code
  Baptism includes the resurrection and the
  redemption; the redemption (takes place) in
  the bridal chamber.

  But the bridal chamber is in that which is
  superior to [...] you will not find [...] are
  those who pray [...] Jerusalem who [...]
  Jerusalem, [...] those called the "Holy of the
  Holies" [...] the veil was rent, [...] bridal
  chamber except the image [...] above.

  Because of this, its veil was rent from top to
  bottom.

  For it was fitting for some from below to go
  upward.

  The powers do not see those who are clothed in
  the perfect light, and consequently are not
  able to detain them.
#+END_SRC

** The way I slept
It honestly mattered, but I think it was surely predestiny.

#+BEGIN_SRC text -n :async :results verbatim code
  One will clothe himself in this light
  sacramentally in the union.

  If the woman had not separated from the man,
  she should not die with the man.

  His separation became the beginning of death.

  Because of this, Christ came to repair the
  separation, which was from the beginning, and
  again unite the two, and to give life to those
  who died as a result of the separation, and
  unite them.

  But the woman is united to her husband in the
  bridal chamber.

  Indeed, those who have united in the bridal
  chamber will no longer be separated.

  Thus Eve separated from Adam because it was
  not in the bridal chamber that she united with
  him.
#+END_SRC

- This document describes the bridal chamber:

- [[https://mullikine.github.io/ox-hugo/The%20Valentinian%20Bridal%20Chamber%20in%20the%20Gospel%20of%20Philip.pdf][The Valentinian Bridal Chamber in the Gospel of Philip]]

This is my visceral experience of the Bridal Chamber.

- [[https://mullikine.github.io/posts/astral-projection/][Astral Projection // Bodacious Blog]]
- [[https://mullikine.github.io/posts/astral-projection-pt-2/][Astral Projection Pt. 2 // Bodacious Blog]]

** [[https://blogs.ancientfaith.com/glory2godforallthings/2020/04/13/in-the-maw-of-the-bridal-chamber/][In the Maw of the Bridal Chamber]]

#+BEGIN_SRC text -n :async :results verbatim code
  It is a hymn of deep irony and paradox.

  The “Bridal Chamber” carries a double meaning.

  It is, at once, the place of mystical union
  between Christ and His Bride (the Church).

  At the same time, it is the grave of Christ
  Himself.

  For that mystical union with Christ begins by
  being “buried with Christ in His death” (in
  Holy Baptism).

  The marriage of Christ and His Bride is in the
  paradox of the hideous maw of death’s domain,
  at the same time the place of Christ’s utter
  triumph over every adversary.

  We are not removed from that terrible place –
  we are healed precisely there.

  The resurrection of Christ begins in the tomb.
#+END_SRC

There was no 'ceremony' that I followed.

Whatever happened, happened spontaneously and changed me.

It's surely something of an event at a higher dimension, and a mystery, which I am confident of in retrospect.

# ** Alchemical marriage with an 'angel of the Savior'
# It's possible this is event unites a holy
# angel with a select Christian to empower them
# to carry out the plan.

# I just don't know how it all works but it's a
# mystery I want to understand.

# - [[https://mullikine.github.io/ox-hugo/The%20Valentinian%20Bridal%20Chamber%20in%20the%20Gospel%20of%20Philip.pdf][The Valentinian Bridal Chamber in the Gospel of Philip]]

# I don't understand yet so I'll leave it there.

# # Irenaeus taught that when Valentinians “at
# # last achieve perfection, [they] shall be given
# # as brides to the angels of the Savior”.

# # Now if it is the case that the alchemical
# # marriage happens with an angel, then I have a hunch
# # I've seen said angel - 3 times.

# # If it improves my case I think I've seen
# # 'heavenly' angels before. Plus I have a lot of
# # evidence to suggest this is what happened.

# # The way the doors opened, for example.

# # + Much like the Angel and Peter :: [[https://www.youtube.com/watch?v=Rr7Udj8lEUU][Peter in Jail - YouTube]]

# # This is the point at which God freed me from
# # the prison of this reality, perhaps.

# # I want to differentiate between angels that can
# # no longer ascend to the heavens and those who
# # still can, and also angels of the light and of
# # the darkness, since I presume dark angels
# # cannot see ones clothed in light, save for a Mediator (Christian).

# # I wonder if it's Jophiel.

# # - https://en.wikipedia.org/wiki/Jophiel

# # # This person has red hair and walks very hastily and
# # # confidently, knows that I know I think, and appearance only started
# # # happening *after* the Holy Baptism. She looks a lot like Melee;
# # # I guess that says something!

# # I like the sounds of Jophiel. But there could
# # be the number of as many as a third of the
# # stars in the sky.

# # I guess it's a mystery!

# # It's surely something of an event at a higher dimension.
# # In retrospect I am confident.

# # The Gospel of Philip is actually quite reserved and straight-forward.
# # It's not filled with the over-explanation of full-on Gnosticism.
# # I trust it.

# # Perhaps it's fine to simply marvel at the mystery of whatever is going on, and discover as I go.

# # Record and observe.

# # However, this gives me greater confidence that now that I believe I have done it,
# # With the aim of recreating a bridal chamber ceremony or process, I guess I'll try to fill in the blanks from the Gospel of Philip!

# # Only with revelation from God, of course, if He allows it

# # [[./Great-Mystery-Marriage.pdf]]
